# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
#  and 
# , the first 
#  terms will be:

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

max_value = 4_000_000

# simple fib (n) = (n-1 ) + (n - 2)
def fib(n):
    if n == 0 : return 0
    if n == 1 : return 1
    return fib(n - 1) + fib(n-2)
    
print(fib(10))

def even_fib(max_value):
    a = 1
    b = 2
    next = a + b
    total = 0
    while b <= max_value:
        if b % 2 == 0:
            total += b
        a = b
        next = a + b
        b = next
    return total    

print(even_fib(20))

